name: smart-token-list CI

on:
  pull_request:
    paths:
      - "packages/smart-token-list/**"

env:
  PROJ_PATH: packages/smart-token-list

permissions:
  contents: write
  checks: write

jobs:
  diff-tokens-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          standalone: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm i
      - name: Diff Tokens Test
        run: |
          cd "${PROJ_PATH}"
          pnpm run diffTokens
          pnpm test
